// src/data.js
export const jobs = [
  {
    id: 1,
    title: "Frontend Developer",
    company: "Tech Corp",
    image: 'https://dcassetcdn.com/design_img/2428705/517402/517402_12715345_2428705_8d7126a1_image.jpg',
    location: "New York",
    type: "Full-time",
    experience: "Mid-Level",
    salary: "Not disclosed",
    posted: "Few Hours Ago",
    rating: 4.5,
    reviews: 120,
    description:
      "We are looking for a skilled Frontend Developer to create engaging user interfaces. Experience with React and modern web technologies is required.",
    tags: ["frontend", "react", "javascript", "web development"],
  },
  {
    id: 2,
    title: "Backend Developer",
    company: "InnovateX",
    location: "Remote",
     image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjLwLv0P1axsdWityopylqjOOMwrORuFH-W-eLOE4qotVJal3sEjvxJuPHWw0OQbqNzT8&usqp=CAU',
    type: "Remote",
    experience: "Senior",
    salary: " 100k -  130k",
    posted: "5 days ago",
    rating: 4.8,
    reviews: 250,
    description:
      "Join our team as a Backend Developer to build scalable APIs and services. Proficiency in Node.js and database management is essential.",
    tags: ["backend", "node.js", "api", "database"],
  },
  {
    id: 3,
    title: "UI/UX Designer",
    company: "Designify",
    location: "San Francisco",
     image: 'https://cdn.logojoy.com/wp-content/uploads/2018/05/30162614/1433.png',
    type: "Part-time",
    experience: "Entry-Level",
    salary: " 60k -  80k",
    posted: "1 week ago",
    rating: 4.2,
    reviews: 80,
    description:
      "We need a creative UI/UX Designer to craft intuitive designs. Experience with Figma and prototyping tools is preferred.",
    tags: ["ui/ux", "design", "figma", "prototyping"],
  },
    {
    id: 4,
    title: "Full Stack Developer",
    company: "DevHub",
    location: "Austin",
     image: 'https://cdn.logojoy.com/wp-content/uploads/2018/05/30162700/759-768x591.png',
    type: "Full-time",
    experience: "Mid-Level",
    salary: "90k - 110k",
    posted: "2 days ago",
    rating: 4.6,
    reviews: 180,
    description:
      "Seeking a Full Stack Developer with experience in MERN stack. Should be able to handle both frontend and backend responsibilities.",
    tags: ["fullstack", "mern", "mongodb", "express", "react", "node.js"],
  },
  {
    id: 5,
    title: "Data Scientist",
    company: "DataNest",
    location: "Boston",
     image: 'https://marketplace.canva.com/EAF1kJubgwA/1/0/1600w/canva-blue-and-white-modern-technology-company-logo-fAFQqyuW2Co.jpg',
    type: "Full-time",
    experience: "Senior",
    salary: "120k - 150k",
    posted: "3 days ago",
    rating: 4.7,
    reviews: 200,
    description:
      "Looking for a Data Scientist skilled in Python, ML models, and data analysis. Experience with large datasets is a plus.",
    tags: ["data science", "python", "machine learning", "analytics"],
  },
  {
    id: 6,
    title: "Mobile App Developer",
    company: "Appify",
    location: "Seattle",
     image: 'https://cdn.logojoy.com/wp-content/uploads/2018/05/30162700/759-768x591.png',
    type: "Contract",
    experience: "Mid-Level",
    salary: "70k - 100k",
    posted: "1 day ago",
    rating: 4.4,
    reviews: 95,
    description:
      "Hiring a Mobile App Developer to build iOS and Android apps using React Native. Cross-platform experience is essential.",
    tags: ["mobile", "react native", "ios", "android"],
  },
  {
    id: 7,
    title: "DevOps Engineer",
    company: "CloudSync",
    location: "Remote",
    type: "Remote",
     image: 'https://cdn.logojoy.com/wp-content/uploads/2018/05/30162614/1433.png',
    experience: "Senior",
    salary: "130k - 160k",
    posted: "4 days ago",
    rating: 4.9,
    reviews: 220,
    description:
      "DevOps Engineer with expertise in AWS, CI/CD, and Docker/Kubernetes. Must have hands-on experience with infrastructure automation.",
    tags: ["devops", "aws", "docker", "kubernetes", "ci/cd"],
  },
  {
    id: 8,
    title: "Product Manager",
    company: "BuildWell",
    location: "Chicago",
    type: "Full-time",
     image: 'https://marketplace.canva.com/EAF1kJubgwA/1/0/1600w/canva-blue-and-white-modern-technology-company-logo-fAFQqyuW2Co.jpg',
    experience: "Mid-Level",
    salary: "110k - 130k",
    posted: "1 week ago",
    rating: 4.3,
    reviews: 140,
    description:
      "Seeking a Product Manager to lead agile teams, manage product roadmaps, and communicate with stakeholders. SaaS experience is a plus.",
    tags: ["product", "management", "agile", "saas"],
  },
  {
    id: 9,
    title: "QA Engineer",
    company: "Testify",
    location: "Denver",
    type: "Full-time",
     image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjLwLv0P1axsdWityopylqjOOMwrORuFH-W-eLOE4qotVJal3sEjvxJuPHWw0OQbqNzT8&usqp=CAU',
    experience: "Entry-Level",
    salary: "60k - 75k",
    posted: "6 hours ago",
    rating: 4.1,
    reviews: 60,
    description:
      "Looking for a QA Engineer to write and maintain automated tests. Experience with Cypress or Selenium preferred.",
    tags: ["qa", "testing", "automation", "selenium", "cypress"],
  },
];