export const jobs = [
  {
    id: 1,
    title: "Product Manager",
    company: "InnovateX",
    image: "https://dcassetcdn.com/design_img/2428705/517402/517402_12715345_2428705_8d7126a1_image.jpg ",
    location: "New York",
    type: "Full-time",
    experience: "Mid-Level",
    salary: "110000 - 130000",
    salaryNumber: 120000,
    posted: "Few Hours Ago",
    rating: 4.6,
    reviews: 150,
    description: "We are looking for a skilled Product Manager to lead cross-functional teams, define product strategy, and drive roadmap execution. Experience in Agile environments preferred.",
    tags: ["product", "management", "agile", "strategy"],
    remote: false,
  },
  {
    id: 2,
    title: "UX Designer",
    company: "Designify",
    location: "Remote",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn :ANd9GcSjLwLv0P1axsdWityopylqjOOMwrORuFH-W-eLOE4qotVJal3sEjvxJuPHWw0OQbqNzT8&usqp=CAU",
    type: "Remote",
    experience: "Senior",
    salary: "90000 - 120000",
    salaryNumber: 105000,
    posted: "1 day ago",
    rating: 4.5,
    reviews: 100,
    description: "Join our team as a UX Designer to create intuitive user experiences. Proficiency in Figma, wireframing, and user research is essential.",
    tags: ["ux", "design", "figma", "user research"],
    remote: true,
  },
  {
    id: 3,
    title: "Brand Manager",
    company: "CreativeCo",
    location: "San Francisco",
    image: "https://marketplace.canva.com/EAF1kJubgwA/1/0/1600w/canva-blue-and-white-modern-technology-company-logo-fAFQqyuW2Co.jpg ",
    type: "Full-time",
    experience: "Mid-Level",
    salary: "85000 - 105000",
    salaryNumber: 95000,
    posted: "2 days ago",
    rating: 4.4,
    reviews: 90,
    description: "Seeking a Brand Manager to develop and execute marketing strategies that strengthen brand identity. Must have strong communication and project management skills.",
    tags: ["brand", "marketing", "strategy", "management"],
    remote: false,
  },
  {
    id: 4,
    title: "UI Designer",
    company: "PixelWorks",
    location: "Austin",
    image: "https://cdn.logojoy.com/wp-content/uploads/2018/05/30162614/1433.png ",
    type: "Part-time",
    experience: "Entry-Level",
    salary: "60000 - 80000",
    salaryNumber: 70000,
    posted: "3 days ago",
    rating: 4.3,
    reviews: 75,
    description: "Hiring a UI Designer to craft visually appealing and responsive interfaces. Knowledge of Sketch, Figma, and design systems is required.",
    tags: ["ui", "design", "figma", "sketch"],
    remote: false,
  },
  {
    id: 5,
    title: "Marketing Coordinator",
    company: "MarketEdge",
    location: "Boston",
    image: "https://cdn.logojoy.com/wp-content/uploads/2018/05/30162700/759-768x591.png ",
    type: "Contract",
    experience: "Entry-Level",
    salary: "55000 - 70000",
    salaryNumber: 62500,
    posted: "4 days ago",
    rating: 4.2,
    reviews: 65,
    description: "Looking for a Marketing Coordinator to assist in campaign planning, content creation, and social media management. Strong organizational skills are a must.",
    tags: ["marketing", "social media", "content", "coordination"],
    remote: false,
  },
  {
    id: 6,
    title: "Customer Success Manager",
    company: "SuccessHub",
    location: "Seattle",
    image: "https://marketplace.canva.com/EAF1kJubgwA/1/0/1600w/canva-blue-and-white-modern-technology-company-logo-fAFQqyuW2Co.jpg ",
    type: "Full-time",
    experience: "Mid-Level",
    salary: "80000 - 100000",
    salaryNumber: 90000,
    posted: "5 days ago",
    rating: 4.5,
    reviews: 110,
    description: "Hiring a Customer Success Manager to ensure client satisfaction, manage onboarding, and foster long-term relationships. SaaS experience preferred.",
    tags: ["customer success", "support", "saas", "management"],
    remote: false,
  },
  {
    id: 7,
    title: "Content Strategist",
    company: "WriteTech",
    location: "Remote",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn :ANd9GcSjLwLv0P1axsdWityopylqjOOMwrORuFH-W-eLOE4qotVJal3sEjvxJuPHWw0OQbqNzT8&usqp=CAU",
    type: "Remote",
    experience: "Senior",
    salary: "90000 - 110000",
    salaryNumber: 100000,
    posted: "6 days ago",
    rating: 4.3,
    reviews: 85,
    description: "Seeking a Content Strategist to develop compelling narratives across digital platforms. Must be experienced in SEO, storytelling, and editorial planning.",
    tags: ["content", "strategy", "seo", "writing"],
    remote: true,
    
  },
  {
    id: 8,
    title: "Project Manager",
    company: "BuildWell",
    location: "Chicago",
    image: "https://dcassetcdn.com/design_img/2428705/517402/517402_12715345_2428705_8d7126a1_image.jpg ",
    type: "Full-time",
    experience: "Mid-Level",
    salary: "95000 - 115000",
    salaryNumber: 105000,
    posted: "1 week ago",
    rating: 4.4,
    reviews: 130,
    description: "Looking for a Project Manager to oversee timelines, budgets, and team coordination. Agile and Scrum experience is highly valued.",
    tags: ["project", "management", "agile", "scrum"],
    remote: false,
  },
  {
    id: 9,
    title: "Graphic Designer",
    company: "VisualEdge",
    location: "Denver",
    image: "https://cdn.logojoy.com/wp-content/uploads/2018/05/30162700/759-768x591.png ",
    type: "Part-time",
    experience: "Junior",
    salary: "50000 - 65000",
    salaryNumber: 57500,
    posted: "1 week ago",
    rating: 4.1,
    reviews: 55,
    description: "We need a talented Graphic Designer to create visual assets for campaigns, branding, and digital ads. Adobe Creative Suite proficiency is required.",
    tags: ["graphic design", "adobe", "branding", "illustration"],
    remote: false,
  },
  {
    id: 10,
    title: "Graphic Designer",
    company: "VisualEdge",
    location: "Denver",
    image: "https://cdn.logojoy.com/wp-content/uploads/2018/05/30162700/759-768x591.png ",
    type: "Part-time",
    experience: "Junior",
    salary: "50000 - 65000",
    salaryNumber: 57500,
    posted: "1 week ago",
    rating: 4.1,
    reviews: 55,
    description: "We need a talented Graphic Designer to create visual assets for campaigns, branding, and digital ads. Adobe Creative Suite proficiency is required.",
    tags: ["graphic design", "adobe", "branding", "illustration"],
    remote: false,
  },
];